name: John Garrigus Homepage
favicon: null
layout_spectrum: 0.00426
typography_spectrum: 0.265765
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#376893'
    - '#8398ac'
    - '#a7c6db'
    - '#4c4d45'
    - '#e5f8fc'
  brandStrength: 0.1875
  lightness: 0.6199713053647429
  saturation: 0.7642637649551034
  rhythmicContrast: 0.34433682868257165
purpose: []
