name: John Garrigus Homepage
favicon: null
layout_spectrum: 0.74574
typography_spectrum: 0.979729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#376893'
    - '#8398ac'
    - '#a7c6db'
    - '#4c4d45'
    - '#e5f8fc'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.344336
purpose: []
